# Generated by Django 3.0.5 on 2020-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='background',
            field=models.CharField(default='Colour One', max_length=50),
        ),
        migrations.AddField(
            model_name='mood',
            name='border',
            field=models.CharField(default='Colour One', max_length=50),
        ),
    ]
